export const arrayBudget = [
  {
    id: 1,
    name: 'barrio1',
    fires: false,
    mercats: false,
    centres: false,
    galeries: false,
    variacio: false,
    quotidia: false,
    score: 3.2,
  },
  {
    id: 2,
    name: 'barrio2',
    fires: false,
    mercats: false,
    centres: false,
    galeries: false,
    variacio: false,
    quotidia: false,
    score: 3.5,
  },
  {
    id: 3,
    name: 'barrio3',
    fires: false,
    mercats: false,
    centres: false,
    galeries: false,
    variacio: false,
    quotidia: false,
    score: 2,
  },
]